FROM node:20 

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY tsconfig.json tsconfig.json
COPY tsconfig.app.json tsconfig.app.json
COPY angular.json angular.json
COPY build.sh build.sh
COPY src src

RUN npm install 

CMD [ "./build.sh" ]

