FROM node:20.11 as builder 

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY tsconfig.json tsconfig.json
COPY src src 

RUN npm install 
RUN npm run build

FROM node:20.11 

WORKDIR /app 

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY run.sh run.sh
COPY --from=builder /app/dist .

RUN npm install --omit=dev

CMD [ "./run.sh" ]

