# This compose file as is will startup a nginx reverse proxy that serves both the Angular SPA application as well as the Express backend in a secure context using an autatically renewable ssl certificate.
# Check all the environement files found in /prod-configs and configure the required values. Some env files replace the default ones in frontend/backend locations. 
# 
# stzagkarak@June2024  

version: "3.7"
services:

  # reverse proxy and webserver
  # configures ssl automaticaly
  # binds frontend content on https://your.domain.com/
  # binds backend server on https://your.domain.com/api/
  # check ./prod-nginx-config/user_conf.d for exact nginx config  
  nginx: 
    image: jonasal/nginx-certbot:${NGINX_CERTBOT_VERSION}
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./prod-configs/nginx-certbot.env # ./nginx-certbot config location
    restart: unless-stopped
    volumes:
      - ./instance/nginx/:/etc/letsencrypt
      - ./prod-nginx-config/user_conf.d:/etc/nginx/user_conf.d # ./prod-nginx-config/user_conf.d nginx config location
      - ./angular-demo-frontend/dist:/usr/share/nginx/html # frontend files
    depends_on:
      - frontend-builder
    networks:
      - intranet

  # builds and runs you backend code in **internal** port 8181
  express-server:
    build: ./express-backend
    ports: 
      - "8181:8181"
    env_file:
      - ./prod-configs/backend.env # ./overwrite backend .env file with ./prod-configs/backend.env
    restart: unless-stopped

  # builds your frontend application and "places" it on the nginx html folder
  # will use the environment.ts file located on the prod-configs folder
  frontend-builder:
    build: ./angular-demo-frontend
    volumes:
      - ./prod-configs/angular_environment:/app/src/environments # overwrites angular environment conf file
      - ./angular-demo-frontend/dist:/app/dist

networks:
  intranet: